version: "3.7"
name: prism-core
services:
  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    restart: always
    networks:
      - prism-network
    ports:
      - "2222:2222"
    environment:
      PORT: 2222
      CONFIG_URL: /swagger-config.yaml
    volumes:
      - ./swagger-config.yaml:/usr/share/nginx/html/swagger-config.yaml
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    hostname: rabbitmq
    networks:
      - prism-network
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    env_file:
      - ../backend.env
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    networks:
      - prism-network
    ports:
      - "3030:3000"
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/etc/grafana/provisioning
    env_file:
      - ../backend.env
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: prometheus
    networks:
      - prism-network
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
networks:
  prism-network:
    external: true
    name: prism-network