version: "3.7"
name: prism-core
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq
    restart: always
    env_file:
      - ../.env
  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: always
    depends_on:
      - prometheus
    volumes:
      - ./grafana:/etc/grafana/provisioning
    env_file:
      - ../.env
    ports:
      - "3030:3000"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    hostname: prometheus
    ports:
      - "9090:9090"
      - "9091:9091"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml


