version: "3.7"
name: prism-authentication
services:
  app:
    container_name: "prism-authentication"
    image: "prism-authentication"
    build: ./
    ports:
      - "8090:8090"
    depends_on:
      - redis
      - postgres
    env_file:
      - ../../.env
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/Prism
      REDIS_HOST: redis
  redis:
    container_name: redis
    image: redis
    hostname: redis
    restart: always
    env_file:
      - ../../.env
    ports:
      - "6379:6379"
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Prism