version: "3.7"
name: prism-messenger
services:
  app:
    container_name: prism-messenger
    image: d4c/prism-messenger:latest
    build: ./
    restart: always
    depends_on:
      - neo4j
      - minio
    networks:
      - prism-network
      - prism-messenger-network
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    environment:
      RABBITMQ_DEFAULT_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      URL_NEO4J: neo4j://neo4j:7687
      URL_MINIO: http://minio:9000
      REDIS_HOST: redis
  neo4j:
    container_name: neo4j
    image: neo4j
    restart: always
    hostname: neo4j
    networks:
      - prism-messenger-network
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    env_file:
      - ../../.env
  minio:
    container_name: minio
    image: minio/minio
    restart: always
    hostname: minio
    networks:
      - prism-messenger-network
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address :9001
    env_file:
      - ../../.env
  minio-bucket:
    container_name: minio-bucket
    image: minio/mc
    networks:
      - prism-messenger-network
    depends_on:
      - minio
    env_file:
      - ../../.env
    entrypoint:
      - /bin/sh
      - -c
      - |
        /usr/bin/mc config host add local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        /usr/bin/mc mb -p local/prism-bucket;
networks:
  prism-network:
    external:
      name: prism-network
  prism-messenger-network:
    name: prism-messenger-network